version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      DB_TYPE: sqlite
      DB_DATABASE: data/database.db
      DB_SYNCHRONIZE: true
    volumes:
      - .:/usr/src/app

    ports:
      - '3001:3001'
